Adding ResultStorageEngine Support in AsyncQueryThread
yahoo/elide pull request #1532
Opened 2020-09-12 03:07 UTC by moizarafat

Co-authored-by: chandrakaran

Resolves #<issue number> (if appropriate)

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-09-15 18:32 UTC, aklish requested changes

2020-09-15 18:32 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
> +            queryResultObj.setResponseBody(responseBody);
We already did this on line 118.

2020-09-15 18:32 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
> +            observableResult = convertJsonToCSV(responseBody);
This conversion is not save to do in memory.  We do this before checking if the type is download or not.

2020-09-15 18:32 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
> +            queryObj.setResult(queryResultObj);
Why do we only set the result for downloads?

2020-09-15 18:32 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
> +        return Observable.using(
This doesn't look right to me.   We shouldn't be handling the entire response body here and convert it to CSV.  We should only convert one row at a time.

2020-09-18 15:09 UTC, moizarafat commented on elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/AsyncIT.java
> +    @Tag("skipInMemory") //Without an ORM, there is nothing to hydrate the excluded entity
remove this, as we dont have DB dependency for result storage engine anymore.

2020-09-18 15:10 UTC, moizarafat commented on elide-graphql/src/main/java/com/yahoo/elide/graphql/QueryRunner.java
> +            if (isMutation(query)) {
graphQLQuery.isMutation can be used.

2021-02-15 18:16 UTC, closed without merging