Jpa entity graph
yahoo/elide pull request #1637
Opened 2020-11-04 22:20 UTC by Chandrasekar-Rajasekar

## Description
Prefetch an attribute that has a to-Many relationship with the queried Entity in order to avoid n + 1 problem. This operation is done by passing a JPA Entity Graph containing the to-many relationship attribute along with the query. A relationship is added to the JPA Entity Graph if the following conditions are satisfied. 

- The relationship has to be present in Entity Projection
- The relationship type should be ToMany and not computed relationship
- The relationship Entity should not be presnet in dirtyResource. (no mutable operation is done on the relationship entity in this request)
- If the relationship Entity is presnet in dirtyResource, then the relationshipship should have CASCADE.ALL cascade type.

## Motivation and Context
This change solves n + 1 problem.

## How Has This Been Tested?
IT test

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-11-05 17:44 UTC, aklish requested changes

2020-11-05 17:44 UTC, aklish commented on elide-core/src/main/java/com/yahoo/elide/ElideSettings.java
> +    @Getter private final boolean enableJPAFetchToManyRelationship;
maybe change to useJpaEntityGraphHint

2020-11-05 17:44 UTC, aklish commented on elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java
> +            if (cascadeType == CascadeType.ALL) {
Do we need cascade all or can this also work with other cascade types?

2020-11-05 17:44 UTC, aklish commented on elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
> +                    && entityGraph != null) {
Move construction of the graph inside this if block.

2020-11-05 17:44 UTC, aklish commented on elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
> +            RelationshipType type = dictionary.getRelationshipType(entityClass, relationshipName);
Rather than looking up this information the dictionary (name and class of the relationship), you can get it from the entity projection.

2020-11-05 17:44 UTC, aklish commented on elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
> +                        .anyMatch(resource -> resource.getType().equals(relationshipClassName));
Maybe add a method to persistentResource isDirty.

2020-11-05 17:44 UTC, aklish commented on elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
> +                if (!isDirtyResource || dictionary.cascadeAll(entityClass, relationshipName)) {
Why do we need cascade all again?

2020-11-05 17:44 UTC, aklish commented on elide-datastore/elide-datastore-jpa/src/main/java/com/yahoo/elide/datastores/jpa/transaction/AbstractJpaTransaction.java
> +                    entityGraph.addAttributeNodes(relationshipName);
Why not add all the projection attributes and relationships?  Also, can this recurse?

2021-03-02 06:55 UTC, thaingo commented
May I know if this is still in Elide 5 roadmap @aklish ?

2021-03-02 16:22 UTC, aklish commented
@thaingo Unfortunately, the entity graph didn't work in the general case. @Chandrasekar-Rajasekar will post some details to the ticket.  

We've tried a few other options, but I no longer believe Hibernate can support this use case.  It's possible another ORM has better support.  Alternatively, I updated the contract for the `DataStoreTransaction` in Elide 5 that would enable some other workarounds.

One of them is to always use the proxy object (and filter, sort, & paginate) in memory whenever we are fetching a collection of collections.  This would be a very small change we could put behind a feature flag.

2021-03-02 17:04 UTC, Chandrasekar-Rajasekar commented
The problem we faced with JPA Entity Graph is that we can't tell the JPA to fetch a relationship based on a filter. Without this, there is a risk of loading a large number of records in memory even though we only need a small chunk of it. 

Another problem is we can only add 1 to-Many relationship to an entity graph, to avoid either MultipleBagFetchError or explosion of data due to cartesian product.

2021-03-03 02:42 UTC, thaingo commented
Many thanks to @aklish and @Chandrasekar-Rajasekar for the detailed information.

> One of them is to always use the proxy object (and filter, sort, & paginate) in memory whenever we are fetching a collection of collections. This would be a very small change we could put behind a feature flag.

Looking forward to this workaround.

2021-03-04 19:52 UTC, aklish commented
> Many thanks to @aklish and @Chandrasekar-Rajasekar for the detailed information.
> 
> > One of them is to always use the proxy object (and filter, sort, & paginate) in memory whenever we are fetching a collection of collections. This would be a very small change we could put behind a feature flag.
> 
> Looking forward to this workaround.

#1876 has the workaround. @thaingo

2021-03-05 14:51 UTC, thaingo commented
> #1876 has the workaround. @thaingo
Its great and looks promising. Thank you @aklish

2021-03-09 21:25 UTC, aklish commented
Fixed another way: #1876

2021-03-09 21:25 UTC, closed without merging