Async cache setting
yahoo/elide pull request #1736
Opened 2020-12-24 04:52 UTC by AvaniMakwana

Resolves #1537  (if appropriate)

## Description
Add 'bypassCache' property to Async to enable/disable caching.

## Motivation and Context
Enable / Disable Caching via Async properties

## How Has This Been Tested?
Unit tests included.

## Screenshots (if appropriate):

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-12-28 15:45 UTC, moizarafat commented on elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneAsyncSettings.java
> +        return true;
Default should be false.

2021-01-04 17:47 UTC, moizarafat approved these changes

2021-01-05 16:30 UTC, aklish requested changes

2021-01-05 16:30 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
> +        bypassCacheMap.put("bypasscache", Arrays.asList(String.valueOf(service.isBypassCache())));
Won't this always override the cache?  I don't think this is the behavior that we want.

2021-01-05 16:30 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/AsyncQueryThread.java
> +            response = executeJsonApiRequest(service.getElide(), user, apiVersion, requestUUID, bypassCacheMap);
Instead of naming the variable bypassCacheMap, call it headers.  It is a better reflection of what the map represents.

2021-01-07 17:13 UTC, AvaniMakwana commented
Closing since we are going to enable / disable caching based on Max cache size property, not on/off property

2021-01-07 17:13 UTC, closed without merging