add druid dialect with new pagination query structure
yahoo/elide pull request #1761
Opened 2021-01-11 17:47 UTC by Chandrasekar-Rajasekar

## Description
Create Druid dialect in aggregation datastore. 

## How Has This Been Tested?
unit test

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-01-12 15:35 UTC, aklish approved these changes

2021-01-13 16:41 UTC, aklish requested changes

2021-01-13 16:41 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
> +                .groupByClause(String.format("GROUP BY %s", groupByDimensions))
Is there any reason we can't simply do:
.groupByClause(sql.getGroupByClause)
and avoid this extra bit of code here?
What if there are no group by dimensions?

2021-01-14 21:13 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
> +                .projectionClause(sql.getProjectionClause())
Thinking about this, we ought to remove the metrics if possible or replace them with count or something simple.  Imagine if the metric was a data sketch aggregation.  We don't want to do some expensive operation.

2021-01-15 04:13 UTC, Chandrasekar-Rajasekar commented
Couldn't use `groupByClause(sql.getGroupByClause)` for pagination because the main SQL query will not contain group by when a user queries the only dimension and will be in the form 
```
select distinct dims from table 
```
We are generating group by queries for the above cases in pagination.

2021-01-15 15:05 UTC, aklish requested changes

2021-01-15 15:05 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
> +            queries.add(paginationSql == null ? "" : paginationSql.toString());
We don't want to add a query here if we are not running one.  If we return "1" as the rowcount and are not running a query, we'll want to skip adding to the list of queries.

2021-01-19 15:49 UTC, aklish approved these changes

2021-01-19 16:59 UTC, merged