Move Include to package-info
yahoo/elide pull request #1853
Opened 2021-02-20 00:18 UTC by wcekan

## Description
Elide 5.x is not finding the Include annotation in the package-info.

## Motivation and Context
This is a migration problem from 4.x and loss of functionality.

## How Has This Been Tested?
Unit testing.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-02-22 16:00 UTC, aklish requested changes

2021-02-22 17:24 UTC, aklish commented on elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapDataStore.java
> +        for (Package beanPackage : beanPackages) {
How about:

```java
        for (Package beanPackage : beanPackages) {
            Stream<Class<?>> classes;
            if (beanPackage.isAnnotationPresent(Include.class)) {
                classes = ClassScanner.getAllClasses(beanPackage.getName()).stream();
            } else {
                classes = ClassScanner.getAnnotatedClasses(beanPackage, Include.class).stream();
            }

            classes
                .filter(modelClass -> modelClass.getName().startsWith(beanPackage.getName()))
                .map(modelClass -> new ClassType(modelClass))
                .filter(modelType -> dictionary.getFirstAnnotation(modelType,
                        Arrays.asList(Include.class, Exclude.class)) instanceof Include)
                .forEach(modelType -> dataStore.put(modelType,
                        Collections.synchronizedMap(new LinkedHashMap<>())));
        }
```

2021-02-22 22:09 UTC, wcekan commented on elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapDataStore.java
> +        for (Package beanPackage : beanPackages) {
This failed the tests because it is not traversing the subpackage infos.

2021-02-23 20:10 UTC, aklish approved these changes

2021-02-23 20:10 UTC, merged