Refactor legacy hooks
yahoo/elide pull request #1896
Opened 2021-03-10 21:26 UTC by wcekan

## Description
* Multiple legacy life cycle annotations can be on same method.
* Process "this" placeholder correctly in `FilterTranslator` and `Operator`

## Motivation and Context
The 
## How Has This Been Tested?

## Screenshots (if appropriate):

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-03-10 23:13 UTC, aklish requested changes

2021-03-10 23:18 UTC, wcekan commented on elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LegacyTestModel.java
> +    public void fieldMultiple() {
These are coming....

2021-03-11 02:16 UTC, wcekan commented on elide-core/src/main/java/com/yahoo/elide/core/security/checks/Check.java
> +    default boolean runInline() {
Done

2021-03-11 15:31 UTC, aklish requested changes

2021-03-11 15:31 UTC, aklish commented on elide-core/src/main/java/com/yahoo/elide/core/security/checks/OperationCheck.java
> +    public boolean runAtCommit() {
Can we move this into Check as default method?

Then, in FilterExpressionCheck and UserCheck, override it to always return false and make the method final (so it cannot be overwritten).

2021-03-11 16:11 UTC, aklish approved these changes

2021-03-11 16:47 UTC, merged