Support FunctionArguments in HJSON configuration
yahoo/elide pull request #1922
Opened 2021-03-17 17:54 UTC by rishi-aga

One of the PR that Resolves https://github.com/yahoo/elide/discussions/1829

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-03-18 04:49 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DraftV4LibraryWithElideFormatAttr.java
>          builder.addFormatAttribute(ElideGrainTypeFormatAttr.FORMAT_NAME, new ElideGrainTypeFormatAttr());
For builders it reads better to use running adds...
```suggestion
        library = DraftV4Library.get().thaw()

                .addFormatAttribute(ElideFieldNameFormatAttr.FORMAT_NAME, new ElideFieldNameFormatAttr())
                .addFormatAttribute(ElideArgumentNameFormatAttr.FORMAT_NAME, new ElideArgumentNameFormatAttr())
                .addFormatAttribute(ElideCardinalityFormatAttr.FORMAT_NAME, new ElideCardinalityFormatAttr())
                .addFormatAttribute(ElideFieldTypeFormatAttr.FORMAT_NAME, new ElideFieldTypeFormatAttr())
                .addFormatAttribute(ElideGrainTypeFormatAttr.FORMAT_NAME, new ElideGrainTypeFormatAttr())
```
etc

2021-03-18 04:50 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DraftV4LibraryWithElideFormatAttr.java
>          library = builder.freeze();
```suggestion

                .addKeyword(new ValidateDimPropertiesKeyword().getKeyword());
                .addKeyword(new ValidateTimeDimPropertiesKeyword().getKeyword());
                .addKeyword(new ValidateArgsPropertiesKeyword().getKeyword());

                 .freeze();
```

2021-03-18 04:54 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/MessageBundleWithElideMessages.java
>          msgSourceBuilder.put(JavaClassNameFormatAttr.FORMAT_KEY, JavaClassNameFormatAttr.FORMAT_MSG);
same here
```suggestion
                .put(ElideFieldNameFormatAttr.FORMAT_KEY, ElideFieldNameFormatAttr.FORMAT_MSG)
                .put(ElideFieldNameFormatAttr.NAME_KEY, ElideFieldNameFormatAttr.NAME_MSG)
                .put(ElideArgumentNameFormatAttr.FORMAT_KEY, ElideArgumentNameFormatAttr.FORMAT_MSG)
                .put(ElideArgumentNameFormatAttr.NAME_KEY, ElideArgumentNameFormatAttr.NAME_MSG)
                .put(ElideCardinalityFormatAttr.TYPE_KEY, ElideCardinalityFormatAttr.TYPE_MSG)
                .put(ElideFieldTypeFormatAttr.TYPE_KEY, ElideFieldTypeFormatAttr.TYPE_MSG)
                .put(ElideGrainTypeFormatAttr.TYPE_KEY, ElideGrainTypeFormatAttr.TYPE_MSG)
                .put(ElideJoinTypeFormatAttr.TYPE_KEY, ElideJoinTypeFormatAttr.TYPE_MSG)
                .put(ElideJoinKindFormatAttr.TYPE_KEY, ElideJoinKindFormatAttr.TYPE_MSG)
                .put(ElideTimeFieldTypeFormatAttr.TYPE_KEY, ElideTimeFieldTypeFormatAttr.TYPE_MSG)
                .put(ElideNameFormatAttr.FORMAT_KEY, ElideNameFormatAttr.FORMAT_MSG)
                .put(ElideNameFormatAttr.NAME_KEY, ElideNameFormatAttr.NAME_MSG)
                .put(ElideRSQLFilterFormatAttr.FORMAT_KEY, ElideRSQLFilterFormatAttr.FORMAT_MSG)
                .put(JavaClassNameWithExtFormatAttr.FORMAT_KEY, JavaClassNameWithExtFormatAttr.FORMAT_MSG)
                .put(JavaClassNameFormatAttr.FORMAT_KEY, JavaClassNameFormatAttr.FORMAT_MSG)
```

2021-03-18 04:55 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ElideNameFormatAttr.java
> +    public static final String NAME_FORMAT_REGEX = "^[A-Za-z][0-9A-Za-z_]*$";
Consider pre-formatting the regex.
```suggestion
    public static final Pattern NAME_FORMAT_REGEX = Pattern.compile("^[A-Za-z][0-9A-Za-z_]*$");
```

2021-03-18 04:57 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ElideNameFormatAttr.java
>          if (!input.matches(NAME_FORMAT_REGEX)) {
and use the pattern
```suggestion
        if (!FIELD_NAME_FORMAT_REGEX.matcher(input).matches()) {
```

2021-03-18 05:03 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ElideArgumentNameFormatAttr.java
> +        if (!input.matches(ElideNameFormatAttr.NAME_FORMAT_REGEX)) {
```suggestion
        if (!ElideNameFormatAttr.NAME_FORMAT_REGEX.matcher(input).matches()) {
```

2021-03-18 12:04 UTC, wcekan commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ValidateArgsPropertiesKeyword.java
> +            }
Consolidate unnecessary conditional
```suggestion
            node.put(keyword, schema.get(keyword).asBoolean(true));
```

2021-03-22 21:12 UTC, aklish requested changes

2021-03-22 21:12 UTC, aklish commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
> +            ((Join) currentColumn).getRequiredColumnArgs().add(argName);
A couple of problems with this:
1. We don't want to put internal validation logic into public contracts (Join configuration class).
2. validation functions should be idempotent as callers will expect them to be stateless.

We need to find another way to do this.  Maybe we need to parse all the join expressions and pull out their required arguments as step one.  At a later step, we can validate that any column which references the join also has all required arguments.  

We also want to make sure we are not duplicating work done by the SQL Reference Table (which does some validation work as well with respect to cycles).  SQL reference table is the only place today that understand the expansion of a join (joins can depend on other joins and so on).  I think we need to rethink how this validation logic responsibility is shared with the SQL Reference table.

2021-03-22 21:12 UTC, aklish commented on elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
> +        assertEquals("Can't invoke 'revenue' provided in \"sql from='revenueFact' column='revenue[currency:USD]'\" for Column: 'impressionsPerUSD' in Model: 'revenueFact'. Column: 'revenue' is undefi
Models may not come from HJSON.  The returned text should not reference HJSON here.

2021-05-12 14:31 UTC, closed without merging