Elide graphql javadoc warning fixes
yahoo/elide pull request #1951
Opened 2021-03-22 22:17 UTC by vandanabhandari

Resolves #1887 

## Description
Fixes the checkstyle warnings.

## Motivation and Context
Fixes the checkstyle warnings.

## How Has This Been Tested?
`$ mvn -pl elide-graphql clean install
.....
[INFO] --- maven-checkstyle-plugin:3.1.2:check (validate) @ elide-graphql ---
[INFO] Starting audit...
[WARN] /Users/veda/vamsi/projects/yahoo/elide/elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLRequestScope.java:30:12: More than 7 parameters (found 8). [ParameterNumber]
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO]
[INFO] Installing /Users/veda/vamsi/projects/yahoo/elide/elide-graphql/target/elide-graphql-3.8.1-sources.jar to /Users/veda/.m2/repository/com/yahoo/elide/elide-graphql/3.8.1/elide-graphql-3.8.1-sources.jar
[INFO] Installing /Users/veda/vamsi/projects/yahoo/elide/elide-graphql/target/elide-graphql-3.8.1-javadoc.jar to /Users/veda/.m2/repository/com/yahoo/elide/elide-graphql/3.8.1/elide-graphql-3.8.1-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2021-03-22T17:18:22-04:00
[INFO] ------------------------------------------------------------------------`
## Screenshots (if appropriate):

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-03-23 16:55 UTC, aklish requested changes

2021-03-23 16:55 UTC, aklish commented on elide-graphql/pom.xml
> +    <version>3.8.1</version>
Don't pin the version here.

2021-03-23 16:55 UTC, aklish commented on elide-integration-tests/src/test/java/example/models/generics/package-info.java
> + * Copyright 2015, Yahoo Inc.
Copyright exists above.

2021-03-23 16:55 UTC, aklish commented on elide-integration-tests/src/test/java/example/models/versioned/package-info.java
> + * Copyright 2015, Yahoo Inc.
Copyright exists above.

2021-03-23 21:23 UTC, vandanabhandari reviewed
Addressed the comments

2021-03-23 21:25 UTC, vandanabhandari commented on elide-integration-tests/src/test/java/example/models/versioned/package-info.java
> + * Copyright 2015, Yahoo Inc.
addressed and removed

2021-03-23 21:26 UTC, vandanabhandari commented on elide-graphql/pom.xml
> +    <version>3.8.1</version>
oops, sorry abt that. Fixed it

2021-03-24 16:39 UTC, aklish approved these changes

2021-03-24 17:12 UTC, merged