Parameterized Metrics: Aggregation Store Model Changes Set 2
yahoo/elide pull request #1957
Opened 2021-03-24 03:21 UTC by moizarafat

## Description
Continuing with Model changes for Parameterized Metrics.
i) Introduced EntityArguments in EntityDictionary and EntityBinding to capture Table Arguments.
ii) Graqhql Models, EntityProjection etc. capture Entity/Table Arguments and make it query accessible from graphql.
iii) TableMeta, DimensionFormula, MetricFormula now capture the Arguments. 
iv) Table Arguments and Column Arguments are now going to be available to pass thru grapqhl.
v) Miscellanous changes to populate and propagate arguments.

## Motivation and Context
https://github.com/yahoo/elide/discussions/1829

## How Has This Been Tested?
Existing Test pass. New Test cases to be added later.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-03-24 18:51 UTC, rishi-aga submitted a review, later dismissed

2021-03-25 15:49 UTC, aklish requested changes
Overall changes look good.  There are no tests.  Were you going to add those in another PR?  If not, we need unit tests and a few IT tests for all of these changes.

2021-03-25 15:49 UTC, aklish commented on elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
> +                                                                DataFetcher fetcher,
Fetcher is unused here.

2021-03-25 15:49 UTC, aklish commented on elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
> +                    .argument(generator.entityArgumentToQueryObject(clazz, dataFetcher, entityDictionary))
We should do this for relationships as well - not just the root objects.

2021-03-25 19:01 UTC, aklish approved these changes

2021-03-25 19:02 UTC, merged