Test Cases + Enable Namespace in Standalone and Spring
yahoo/elide pull request #2040
Opened 2021-04-29 03:41 UTC by moizarafat

Resolves #2010 

## Description
i) Enable Namespace HJSON Config parsing in Elide Standalone and Spring.
ii) Test cases for Agg Store Changes to add namespace metadata

## Motivation and Context
#2010

## How Has This Been Tested?
Existing and new test cases pass

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-04-29 11:39 UTC, moizarafat commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/NamespaceConfig.java
> +    public String getDescription() {
Keeping Same as Table.

2021-04-29 16:09 UTC, aklish requested changes

2021-04-29 22:50 UTC, aklish requested changes

2021-04-29 22:50 UTC, aklish commented on elide-model-config/src/main/java/com/yahoo/elide/modelconfig/jsonformats/ElideNamespaceNameFormatAttr.java
> +                    + "alaphabets, numbers and '_' only. Name must not be a variant of 'default' with different cases.";
Can these be two different messages for the two different error scenarios?  Also, the second condition is a little hard to follow.  Maybe say something like:  'Name [%s] clashes with the 'default' namespace.  Either change the case or pick a different namespace name.'

2021-04-29 22:50 UTC, aklish commented on elide-model-config/src/test/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidatorTest.java
> +        assertEquals("default", referred.getNamespace()); // Namespace in HJson "DEfault". Matched case insensitively with "default" namespace
Comment is wrong.

2021-04-30 02:02 UTC, aklish approved these changes

2021-04-30 02:02 UTC, merged