httpclient 4.5.13
yahoo/elide pull request #2074
Opened 2021-05-06 01:00 UTC by wcekan

## Description
Avoid CVE-2020-13956
```
httpclient-4.5.3.jar (pkg:maven/org.apache.httpcomponents/httpclient@4.5.3, cpe:2.3:a:apache:httpclient:4.5.3:*:*:*:*:*:*:*) : CVE-2020-13956
```

## Motivation and Context
Security

## How Has This Been Tested?
Unit testing

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-05-06 02:19 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
What requires this?

2021-05-06 03:59 UTC, wcekan commented on elide-datastore/elide-datastore-aggregation/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
avatica-core

2021-05-06 04:15 UTC, wcekan commented on elide-datastore/elide-datastore-aggregation/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
changed scope to runtime to match the dependencies of calcite

2021-05-06 13:36 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
We don't use calcite to make HTTP connections though.  Is there any reason we can't simply exclude it?

2021-05-06 21:43 UTC, wcekan commented on elide-datastore/elide-datastore-aggregation/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
No.  If we mention `calcite` without any mention of `httpclient` the downstream will pull in the `calcite` old version.  They have the option to exclude it, but sadly `maven` does not let us exclude on their behalf.

2021-05-06 23:29 UTC, aklish approved these changes

2021-05-06 23:29 UTC, aklish requested changes

2021-05-06 23:29 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
Can we add a comment:

Avoid CVE-2020-13956

2021-08-16 22:21 UTC, aklish approved these changes

2021-08-16 22:21 UTC, merged