Propogate client query arguments to join tables
yahoo/elide pull request #2095
Opened 2021-05-14 16:05 UTC by rishi-aga

One of the PR that Resolves https://github.com/yahoo/elide/discussions/1829

## Description
Propogate client query arguments to join tables

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-05-14 18:17 UTC, rishi-aga commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
> +                                              this.getColumn().getArguments()));
Getting column projection from queryable's source itself, this column projection will have default/available arguments for the column.  So no need to go-to source for default/available arguments again.

2021-05-17 16:29 UTC, aklish requested changes

2021-05-17 16:29 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
> +    public static Map<String, Argument> mergedArgumentMap(Map<String, Argument> referencedColumnArgs,
javadoc

2021-05-17 16:29 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/ColumnContext.java
> +    public static Map<String, Argument> mergedArgumentMap(Map<String, Argument> referencedColumnArgs,
These function parameters use terms like column but the function is also leveraged for table arguments.  Let's rename these parameters so they make sense in both contexts.

2021-05-17 16:29 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/integration/MetaDataStoreIntegrationTest.java
> +                .get("/table/SalesNamespace_orderDetails?include=argumentDefinitions")
The contract of the API shouldn't change here (should still be argument) even though we changed the model name.  The `@Include` type is still 'argument'.  Not sure why this test is passing.

2021-05-17 19:48 UTC, aklish approved these changes

2021-05-17 20:47 UTC, merged