Redis Result Storage Engine
yahoo/elide pull request #2507
Opened 2022-01-21 04:40 UTC by moizarafat

Resolves #<issue number> (if appropriate)

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-01-24 21:08 UTC, aklish requested changes

2022-01-24 21:08 UTC, aklish commented on elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngineTest.java
> +    public void setup() throws IOException {
We need tests to test the batch reading.

2022-01-24 21:08 UTC, aklish commented on elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngine.java
> +    private static final int BATCH_SIZE = 500;
Can this be configurable?

2022-01-25 04:28 UTC, moizarafat commented on elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngine.java
> +                        recordRead[0] = recordRead[0] + BATCH_SIZE;
Don't think that will work. I have updated the logic with better comments, hopefully that will clarify the logic.

for fewer records than batch size, logic is L-98 to L-100

2022-01-25 15:24 UTC, aklish commented on elide-async/src/test/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngineTest.java
> +        verifyResults("store_results_batch_success", Arrays.asList("hi\nhello", "bye"));
Should there be a newline after hello in this case?

2022-01-25 15:30 UTC, aklish submitted a review, later dismissed

2022-01-25 17:40 UTC, moizarafat commented on elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/RedisResultStorageEngine.java
> +    @Setter private UnifiedJedis jedis;
Switching to UnifiedJedis so we can switch between JedisCluster and JedisPooled according the environment.

https://github.com/redis/jedis/blob/master/README.md
https://github.com/redis/jedis/releases/tag/v4.0.0

2022-01-25 20:09 UTC, aklish approved these changes

2022-01-25 20:09 UTC, merged