Support multiple `JpaDataStore`
yahoo/elide pull request #2998
Opened 2023-05-28 04:06 UTC by justin-tay

In order to support multiple transactional `JpaDataStore` in Spring the `MultiplexManager` needed to be modified to process transactions last-in-first-out instead of first-in-first-out. After making this modification, a test was failing. The test was testing that the previously committed transaction on a `HashMapDataStore` was being reversed by the `MultiplexManager`. Reversing the order meant that the transaction on the `HashMapDataStore` wasn't even being commited, however the data was still modified. The objects retrieved from the `HashMapDataStore` are the same reference from the store, so any modifications to the store actually already modifies the data in the underlying store.

In order to fix this the following things were done to the `HashMapDataStore`.
- A `ReadWriteLock` was introduced so write transactions need an exclusive lock when making modifications
- A rollback implementation similar to what the `MultiplexManager` does to reverse the transaction

The new `HashMapDataStoreTest#testShouldNotReadDirtyData` test demonstrates the issue and the fix.

## Description
- Spring's `JtaTransactionManager` is now supported
- A `@EnableJpaDataStore` annotation is added to make it easy to add and configure multiple `JpaDataStore`. Allows configuring the entity manager, transaction manager or the managed classes.
- Introduced a `DataStoreBuilderCustomizer` and `JpaDataStoreRegistrationsBuilderCustomizer` to allow customization of the autoconfiguration without needed to totally copy and paste the existing codes.
- `MultiplexManager` now processes transactions last-in-first-out.
- `HashMapDataStore` modified for data consistency.

## Motivation and Context
Makes it possible to have multiple transactional `JpaDataStore` in the same transaction. Makes the configuration of `JpaDataStore` easier. 

## How Has This Been Tested?
Tested with unit and integration tests.

In particular the following were tested for Spring
- 2 x `JpaTransactionManager` and 2 x `EntityManagerFactory`
- 1 x `JtaTransactionManager` and 2 x `EntityManagerFactory`

The Atomikos `JtaTransactionManager` was used for the test.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-05-30 19:03 UTC, aklish requested changes
Looked over elide-core only so far.

2023-05-31 03:45 UTC, justin-tay commented on elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapStoreTransaction.java
> +            cacheForRollback(projection.getType(), data);
Have removed the synchronized blocks.

2023-06-03 18:59 UTC, aklish commented on elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStoreTransaction.java
> +                key -> dataStore.beginReadTransaction());
I'm not sure this is correct.  Why a read transaction here?

2023-06-03 20:49 UTC, aklish approved these changes

2023-06-03 23:56 UTC, justin-tay commented
I think the build error is transient. I tried running the failing `example.tests.AsyncTest.testExportDynamicModel` test locally a few times and cannot reproduce it.

2023-06-04 15:15 UTC, merged