Entity scan on non-existing data model package silences error
yahoo/elide pull request #3197
Opened 2024-04-04 12:58 UTC by Doom9527

Resolves #3144

## Description
This PR primarily addresses the scenario where `Elide` is configured with a non-existent data model package. With the updated implementation, `Elide` now fails to start gracefully and throws a runtime exception when encountering an invalid data model package during scanning.

## Motivation and Context
In the `Standalone` or other projects which import `Elide`, the `getAnnotatedClasses` of the `DefaultClassScanner` under the `Elide` is called to scan the package. I add a judgment on the Set, and throw an exception if it is empty.

## How Has This Been Tested?
Please review my PR request and if possible, I will write the testing class again.

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-04-13 17:10 UTC, aklish commented on .github/workflows/ci-cd.yml
> +name: Elide CI/CD
Elide already has Screwdriver CI/CD for unit and integration tests which cost the company nothing.

2024-04-13 17:12 UTC, aklish commented on screwdriver.yaml
We cannot delete this file.  There have also been hacking attempts of people putting scripts into our CI/CD so only committers can run PR CI/CD to avoid build credentials getting stolen.

2024-04-13 17:12 UTC, aklish requested changes
Code looks good and will approve when screwdriver yaml is added back and github workflows (which are not free) are removed.

2024-04-14 03:03 UTC, Doom9527 commented
Yes, I have added screwdriver yaml back and removed github workflows.

2024-04-20 17:16 UTC, aklish approved these changes

2024-04-20 17:16 UTC, merged